#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"

echo "-----> Installing ffmpeg ..."

FFMPEG_PATH="/usr/local/bin/ffmpeg"

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive
if [ ! -x $FFMPEG_PATH ]; then
    echo "Injected ffmpeg"
fi
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
echo "IMAGE: $IMAGE"
echo "COMMAND: $COMMAND"
ID=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")

# sudo docker exec -it f63710e917d8 bash
#enable logs
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
