#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

echo "-----> Installing ffmpeg ..."

FFMPEG_PATH="/usr/local/bin/ffmpeg"

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive
if [ ! -x $FFMPEG_PATH ]; then
    echo "Injected ffmpeg"
fi
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
ID=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
